services:
  openweb-ui:
    build:
      context: .
      dockerfile: owebui.Dockerfile
    container_name: openweb-ui
    environment:
      - DATA_DIR=/assets/data
    env_file:
      - configs/.env.dev
      - configs/.env.secrets
    networks:
      - jungle
    volumes:
      - ollama_data:/root/.ollama/models
      - assets_data:/assets/data
    ports:
      - 80:8080
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  ollama_data: # local models & ollama settings
  assets_data: # files/documents store

networks:
  jungle:
    driver: bridge
