services:
  code-monkey:
    volumes:
      - ollama:/root/.ollama
    container_name: code-monkey
    pull_policy: always
    tty: true
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile.monkey
    networks:
      - aether

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/code-monkey'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - code-monkey
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://code-monkey:11434'
      - 'WEBUI_AUTH=False'
      - 'OLLAMA_GPU_DRIVER=nvidia'
      - 'OLLAMA_GPU_COUNT=all'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - aether

networks:
  aether:
    driver: bridge

volumes:
  ollama: {}
  open-webui: {}
